# Generated by Django 4.0.4 on 2022-05-31 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0003_alter_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysubscribers',
            name='categoryThrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.category'),
        ),
        migrations.AlterField(
            model_name='categorysubscribers',
            name='userThrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
