# Generated by Django 4.0.4 on 2022-05-31 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0004_alter_categorysubscribers_categorythrough_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='categories', related_query_name='category', through='newsapp.CategorySubscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
